apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
stringData:
  admin.password: ref+sops:///nix/store/fvdbpgqn25h8fg1kfd2cfq2l5r57jhqv-k8s-secrets.enc.yaml#argocd-admin-password
  admin.passwordMtime: ref+sops:///nix/store/fvdbpgqn25h8fg1kfd2cfq2l5r57jhqv-k8s-secrets.enc.yaml#argocd-admin-mtime
type: Opaque
