apiVersion: v1
data:
  admin.password: JDJ5JDEwJFZRZ0p2em5WdWhEYll2ZUl2VXNyMXVLaDBDZ21CS2JXUC5EaEtIMkw1ZnI2ZTZTTEJnUDJp
  admin.passwordMtime: MjAyNi0wMi0xMFQyMjo0MzowN1o=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
