apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-demo
  namespace: argocd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS2oxOGZRdmhTMXExYUt4
        cGpOb0RieGhWWHJ5MktFZU45ZUtRTUFKbFZrCms3b3pvaHJ4d05UWGNrVVhRbXN3
        enREU2M4VnRPMWFHcHArYWJRMy82ZHcKLS0tIE9Rb0tNbURvTm9BN1BBZlRhbzZC
        cTRQZ0JQZmFJSm16VGVEekd3cHZWZ1EK4EMGRyecHxfS//vJG1Yh+HcVcatfYbto
        q4+LfCzvvD5y7GTVQZP6bpZWXC974u7AaIhpW853/jrCxMLsVNuvQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-09T21:41:19Z"
  mac: ENC[AES256_GCM,data:/mUnU4867v51asSOlsP+iFEUzm/jSJTJr3r/J6sVXQczPzJRLBF4ew1C21vFGZnpqyEEU08GhxA+mlb1vINgmscQ4EzcKdGLb5ZemXlSY04Ui8YI4vJG3PtkP+4Ru1nqLDEpdYQmwG+LMXNckeU2CVDxq367BDl+ELbH5YeqAPE=,iv:YyKRg4BFfNHjUrXgXG8dWLQxohK7HIr9FQhtJEiouSY=,tag:J4zjTNL3KviElExc/Hh3Zw==,type:str]
  pgp:
    - created_at: "2026-02-09T21:41:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA8rRqWJQppmwARAAshnMzh1oVdeBM71PzjfDJ+PHcuA8HsrFzaIgLLDmPwpI
        R1jGU+kMLQQT1tn1CRD6Um4LhQrHeVFk1VU0TnrEQv7E60Xf543QwZxXhQwsw840
        BvKxcCtQ8C4qZIM8/xKF7zxchmHr4zgx/41odRGoYCVXZxsrebvuHpgoJ369iASC
        wUTnj0q+1vL9qshWwBfycH3HwyGjQIS2Mof+VMvFEQAC9+nuAIYCRFnJcxBRatK/
        UuzVXSQIWpLk51312cYKXn3fljueGWAh6676C5Nu7XVmMbUiOGyM+uIqthalpSz6
        hF+tPZbI+nVPA0AHr+81J0gOtn+mfesR2ZDQV/YgXNU403RjVpPgjlwQlF8gYXWD
        KdBAhpol6KvuIN9aYHORfid8LRHXEqxY4rJn9RuEji3i95pgSvScStP6V258j4ui
        JAW2+lX4+jyivyFKiHrX7jReDRfF++FjWA5pFWr6yev4DUK76vRSgLR73ohG05Hn
        6WEwvI9BvQfFd0gWhW8+5V2z9cG4CEXswOG6pupwY8X4C9zQfAq5gmi0A7PiJH9J
        McxAQawo8ULo+9u3qakvY6g1AkR1e3zjXlAB4OCHQmZd2HLeTRdH4BTwM3td0H63
        yHDyuOisF4pt1ovlXsiK/jJPEfJoWJx3TMxqJR4UrfCm2qgfdGRuAp6qEPNR7OrS
        XgF6GCOUFmr19c/o0OJqB4puZe0mB4+X3dZxP5khS/meBtRJdUf6wqs7E3R1nNCN
        hgdTpzR0G5/gL2yaIbASxuJzRnc8NaMElH0CPrfSX1WymeyBrwGl0YH0yhOBSp0=
        =/QLx
        -----END PGP MESSAGE-----
      fp: 7ABBD02D2A9F7976BA091C55E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
    - name: argo-demo
      stringData:
        password: ENC[AES256_GCM,data:DsLooh4q+w00LcQ=,iv:amc6L9wpc0b4vlP5YPSExJKaNUAXe82rgjTZkk0jqIM=,tag:9zTgOMG5Uqcs/WBJF+7zug==,type:str]
