apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 41b4e5f54c0c13ab7e02b3895756f250d25aeab11e91c8b9132854e168b92d7f
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c3hTSkpJU21EWFJMK0hq

      UGlpQTlpR0pFbnYrYWpsSzdMRkZXUExVQ1ZjCjRzUmdtSUV1WGF0SnM1QU81Yncr

      TGRDRys4c3l5eCtiS21hQTlUTHUxMncKLS0tIHd4QTBncTc4SStJOTRGbTB6NHp4

      emNGaGxEMHNFWFNNVmg3WVpBK3gybkkKmfG7nbmCUr5Gm+NvfKfFe+pVYmgcIeLA

      xgYOXHmHCIQKl1+HTgTd2i0Ld2wxIErDt+0KIibJXYJjBW8/vVrT/w==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T00:44:25Z'
  mac: ENC[AES256_GCM,data:tkpq8v5I1HOzMVr8dDUard3IlDLrF9S7Nzj4ox37zjbB/Cc2EDkw1hbmhJCkGDmyHCPq4haX35sz51mrysE6jJcDHFXFZlG1TqrTXypXsaJMJKvYa2l5kzQ2jcZKRZ6m+6l0/no366sAcPGBSWh1V8Tcx54FL5F4mq0SmEZcFHQ=,iv:cZ9dyjKkndJMqLvkM2wNij1wvJLNb4DXcnFGDv7ujZQ=,tag:FzDkmFnLCcsqqgra2coh0Q==,type:str]
  pgp:
  - created_at: '2026-02-19T00:44:25Z'
    enc: '-----BEGIN PGP MESSAGE-----


      hQIMAwAAAAAAAAAAAQ/8CRYR7oqEy9M3mo7I+sEXF+H+LAhsweZol038NmBnOAIa

      qY52BTwgk0A9i4+o5zNsNFooy0r/zio6PyNt2T72ZroMNj+kDhIpP00lbGGBtX2l

      8Gi3HAXcG/bswlte4yICQ/Ffj9QczJ26xwKGY7TDFnIFoKwTY/6ZCuPPYAy9HsBS

      uahZ4+Yv20Yc225FJ9htLoIr/AnhDfZP8sj3Fa3v3G+336Hh5zUUoNSw7a7sxUJf

      fjejDSIlBL0yVKC7o35xmuwB68UOBagI82bKi+gwQKw6O9nZQLE6P8Sex53S7Cph

      0lgQ430BFdKBkxf6FVRB9TDY4GHX7oynWkVhkxUtrqeRUz61TEKTC2z4kpFDC6q1

      kZllTKfMSWFw6tJA3tKSkIkbLUH/cPx2xhvuB9ptMGPEKdnGdJgVUfedM9NcFtjA

      bjw04wvDpM0LBR5BxTiSX5oNB9Eo8pGUGG/kTgVc4k8V47OCiR5Nv+6YayKc1FfA

      q10fKyVA7j2PExbTy7OQAKTW5VwAfFaacvIVXa9PAw1ogqBJrafM1OUJEES6gLhR

      hQa1qZwRQhLlJFA5a3tzP0L+J1vrTOcbE/cg5dkZEPkL/i6skfDrBYHJUlYIo1B/

      ZNInMKzUSk5CUlWsV3s0kMJHr5nu7iFziAi5KyjofWjrXb4EoSn++2fJc+MwjIjS

      XAEIjg5OXhOJaQlT+GG65AXE7qh6CIL244ajxja4LoRO1YF2wC/+7MgmHuSOsM91

      m548C4v+txw46e1GFXpLd4R5dfP34S8Q3PgmQHM/ErQZydlucZcbvcARxh5y

      =3bIa

      -----END PGP MESSAGE-----'
    fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:iZO+r7xPAHfpTrPNeX81NMwNWWXx749JndhCAY3BDgEMqttJNCQ6LLlBZfNMSxFFuQaM6rKHN1wHuekL,iv:vKh0zEN2QgB8u1SDwbGK+PsmEBR5F7glG0wViAItwIc=,tag:uePfUBaeJyI08OOvCcJ9KA==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:jhus+trk1dB30ic9ZllqYsH4QULpfA==,iv:BqWj7Hoo0YtPUtUdbp/ik1+J+vqA6f6gjwjnRIw13F4=,tag:P7otsZqxhboaTnMUcTeEZw==,type:str]
    type: Opaque
