apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: dc88d6133f16c71969012199de76f8a425aefde78f3166ff7b982980e1591030
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2tnU1ZVL0w5RllQdkxF

      Yk5VaFhNZWxVV05lMTN0ald4R01hRHIxUW1VCmlZSmV5bUQ5SWErY1RWQWlyMWtw

      dGpZRzh6OERWS2tEM2NjVFFGZE9BR00KLS0tIDVzYjFCTmVNWHhkaGxFSUw0KzRM

      bmtVU0pLYUUzbmxCVFZ5MXdyZ3hpdlEKPmcl7buHC1ms44mYNjL26uBDcxnawnOe

      KY86NytQr3+phuPvikBY6ZDcJiVocj1B60Eolr7qsSIxHstVPE9xgw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:50:48Z'
  mac: ENC[AES256_GCM,data:z5IYbF6AasDzzNQKRtGX3SlgRPajpydCbaweEHjZeX9acoa9s9gInIfhVqmzV5y1ESYSepzYQGQQdwrbZTXFdXZPi9ILNInYcfPi3A2BQpriLwODohCadfpdFb1I4UMOtAL0uU3jMlTSDPUMS1+Wr5W4Wf/dAv001wHnU9W0ze0=,iv:DOcqyIgphyvwCHpSfxQzQv3UzM2LV3yFAFgYVxqMCTo=,tag:bzf+8D5t04bBiUm3gpgmmQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:bA5K5lGvQFf2LKz0SwSfpsQSeUJaRI4sYZegpo+5v9kyB59oekSapi4P6s0M7FwFSsURrn5mJKntfw5d,iv:1A4WOIyE0nGoyc+knyxM2Yk5tQpAgI+a3QoeiYkzwFc=,tag:jOFG24I3J4w4kQbh41B5dw==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:OhEh/N8wx3fW9k5f4iuPkWPd1pRZhw==,iv:TKwclzNcS08Ljqd79lG4cTDKRF5dJQbBWK8xcbkd6oc=,tag:NcHRtXuF1APpLzuuv2whag==,type:str]
      server.secretkey: ENC[AES256_GCM,data:0m3a4bTgDBgGf5W4yRI6/gX+H1sBZP/Qyr/WcdV311RS7H9IKqWQrflHDrY=,iv:RzhLrMgwcoO3VSMOk0usrmJwLl+6tRsVt+dhkDMLmUQ=,tag:ih1UMhmgldcMpd2xP+dF3Q==,type:str]
    type: Opaque
