apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 41b4e5f54c0c13ab7e02b3895756f250d25aeab11e91c8b9132854e168b92d7f
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXc3NVByN0JEZWx6ZlFR

      aG01Q2VyNW1zZTlTSnI1NVE3K3M5NnZNWkhrCjBDUmxUbGVxbXJJdDFkZWZzS3Ar

      N0ZKalRvUDJ0TXdqTnJFMzhIbzZybkEKLS0tIGRPYUFQYW5CN0RJVFpwaHZpc2RX

      T3JDMEc4YndZbDhybjIzQlZRRklubG8KfDKcfVAtlP/ECbrFUE2JQlS89GQ7fTun

      CtMpUoqgjhPyzx0HgpT7SGOOolB9PKLmB8j+G7nUFGH3Z7U0ojYmEg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:11:58Z'
  mac: ENC[AES256_GCM,data:e1KagoWLoS2/Y5Mf27PsCbeDWTa6G8UCNFr7a6/5JNrCPHasQR6DNcT/D1ZxVug17jd6mgmc1T8EGakIzV8/nSX3FApwyTShklspSbq1zLaz82cnIXcTGuKniBBe/U04FPuKhlWz/iInEal31IzxDix7ugW3vggKdvZ3KQSW9uQ=,iv:Soo6Kg2DpHpOVRODCPR3AwPxR34HZfl03wwcwMuBL0k=,tag:He328rbQ1fUoua6sjeJFMQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:akEzXYG2dWPf6fGyz9SOy1xzjKKBu0F+0A2fa6gQuF8T5vYp0mFWP9SP3nfZXAHB68Q+tLnYfFIHZSl7,iv:+ZqB6t/2vTRN1EubVVMImg4ctaRuXnR869hTMwAV1/w=,tag:p1jfMdyS90KWRXjFIks+8g==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:I6ePsKew4dkcgAhuU6uiZdyFXihTUw==,iv:1VixIMq1dvzAzYHrCVj4kpueDjXhbPd9+8WAbS9Wyjo=,tag:k9MsMdvWZTSFoPAbqTP6pQ==,type:str]
    type: Opaque
