apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-demo
  namespace: argocd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYVVIS0Q4M3d3MU1qUEcy
        cGt3eno5cko0NlVPUHdjNmJvMzJMNWc1S2pZCkZwSSsvY1lSSHpRMDdIZVdRejVN
        VWdpRzQ4RzJMOVFkaVllWVQwYnJZK2MKLS0tIHEySDFyaHEzNzdoOGJqRmJDQzZQ
        a2lNeC9LZmptYVMzdE9tcVZTUXVUQXcKHtRHSkKemfk4heYpsD7KMFKS/6FPIj/m
        xrsWfyS6hIOqV/astvDZ7/Z/8O1kFBY9khoV9KjFMSwvOaq43ct0pA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-09T21:51:02Z"
  mac: ENC[AES256_GCM,data:s8xJhCTBksnBP0ddW2HAJlGqgxnqIxjf8oYAJN1yxvZRAFl58Cj/6/LWBVfizg8hAb3Ps1XKiEUyytSoeyZFgtA6HxfYt4BpzfSBEISHXFaqQIKoQrIk9Zml4WW0iZ/UhMYBvphgIVJE+OBXH59rw7hz++WlI2OpHQKjgmEUeGo=,iv:i+0bEC9RzCkCgC5Cs7fjcr1o2cAGJ7DzR8NwN4pqyPk=,tag:L4ceaovmIuI4F53pPveJKw==,type:str]
  pgp:
    - created_at: "2026-02-09T21:51:01Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA8rRqWJQppmwAQ//c9kNxXMuTFi+HFfw6P++hP9eEYaJKnk/C7rDh+mi6bCu
        8m70IqaclQYW6/YRoKtXSKaDjsNMKi9pMBa8qPPiQvk+DQdt7KLrreN1yvxGr50D
        /UAXHzVmN/0h3CA0+qq7RqUIJP7fTirJkcwj2yCOixIYfvBtBUTHrk1fuZMitpHg
        181Ful4KpKfYrRlwDZCvN+xZcwvGyiV9A8ujP8yv/+DEe7AcV6hDrjocy+B6ysAr
        GWHzVLcCKux0yni4iAwgu+BpeI2UA4cuhLe08OCCx/qWMzmmX6yHabwvFwb7tf+e
        qfYhCTbet3x+39mnZDvLp8Uun/I6hd3+UDFrJSc20o1eOmQ2Qz5W5IphX9R9K2Pp
        7+LcT9lqGXIxS3KT9pnGjmkkHPrIQK5q7P/h6baao5D4kdLdw1MRGh7oqmeqVyiH
        NCQOb3mG6ngUUjNXalL9loqpqmaFAl3wgtVZttxiTjN9vqnU7SOzb7tkJmqol5QM
        yJAi6iJ2KliHZbdSHKb+RurKPuZDsgxiykcIUGFvsr4tyXSlRV/yGxPnNnINKS0o
        NLrT3QA+pnfxpVQXQ7u7Os56ZWmA58XyuJ7/iYkL8kr343HXK6OGPlDO2/Fv10TZ
        V7Vd3iklbyvv+Lq3bsPTEbogOU82z0KTTbD/pflADcQqAxMcJwIEJLtFr6ajWRTS
        XgGA+2oQpbWhPUEPGza9zbhMiEcheO8+VCLJQswA2HedRyHC1Q+uWIsJkc7SKUzZ
        lo3sEqDmhfTUqpJTKNZDNqj1UzfdYABz243xs67B7+7zS9KtYgFyRJqcMu4KhvU=
        =MUGn
        -----END PGP MESSAGE-----
      fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
    - name: argo-demo
      stringData:
        password: ENC[AES256_GCM,data:BylF2Bb+EIyfamw=,iv:AofYeVDZCtSIOdhR4d4kO47sy6lu3xjDRL5XTmLEPi8=,tag:M+l/NscrpOLcLRTv5Qv4Ag==,type:str]
