apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 8c6562bbbbda2fdf03f309c2b6c6a514a96f8f6ee93e969eac3bc155e0793646
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVUVxQ0tJMmk5ZjYyV1VU

      TWtocVo1ZGl1K2FKellUcWJIVTkveGJHcno0CmI4RmRTSHd0ZG9KVkZpOEV6MzJN

      b1JzU0RkV2hIQkhpd2IvV1RHeHVPZ1kKLS0tIHZEaFl1MlZvTE1CNHE2SE9wNGxk

      YkpDNGpPeG15akJsSWcySm82NS9pRGsKF6paJ2oXd1nfRym6FlJWAIHBJj9g2qh3

      oV/u/xmkAdgYQ2iAACrfZxpaGLKLgOL0cSHpcAiykfAosIyvBf7nIg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:11:57Z'
  mac: ENC[AES256_GCM,data:iqSmqqJVETaqx74WfxchXE5hEVWJwL+rstnf6UDlQ1zt8KNn4XL2Dc9ihzlhAld7dnraj5Fo2NuUdU5sZYsWEQdwVa8fW8BjFc9tJUK1vbF1tyTROftcTxZPNFBCDe94WT/ydZvxCQPO0H8j30b2DbZkRo7iPVYCkQAvGYumB6c=,iv:bsGyp64Ge5E3jwiKDv17352ZtlWos/98+i6cNM6SRsI=,tag:JUXXpPgUWiLYpwMqI0UB4w==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:hjKinTWvSfPiAv5FYk4q58+vGG98ShPzH1mfzKNM,iv:nhLbwooLr9Tto6Rop8dW/qqRsyDQXYjAmxWeP0uomzs=,tag:SrAk+Uf1soCp8+003eC19w==,type:str]
    type: Opaque
