apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-demo
  namespace: argocd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M3RXOEJzNlFXRExObDVB
        WER0STZUa3c5SFdlYlRVeFBvQytZZFZFdFcwCm5HbThINUliKzNkdFY3c25ra0wv
        M3VDMTJKUXFNMHRCcjk2SDZyZUNhcmMKLS0tIFZnc1pmWitjYStRbU9DNUlqQkwz
        cForK0VJMXlSYjYrVElNOU1CaUZKMk0KE13YyURDnqG80LHM68OXDPdkuJmpo77w
        TSVMr3Lig42Vwbp63wJMHoMxRtZx/q06XxBTiatvzjkSVcs6tJtqhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-09T21:48:51Z"
  mac: ENC[AES256_GCM,data:Fo1NoSRcGFhRX6KE259quTVmTjmwP8f50VUgq7ay99xmkhmeLyN8tComf5PXLrbfi4aQKUD0Wnf5wbR9cVPK/T+nHBbyFgHjUELXoRM5LsbjHPQnW9245nhx/5vzDXA/dwWKvqMCwBxfUpL7qZkYBt68QALOXxxUzeYXRDYMdP0=,iv:99DRzOywnzBpjXzDJjrv7/Q4wx2uxxUiJUOGcSeaTtg=,tag:nEFjlPjzd2vivqYnlNympA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: argo-demo
      stringData:
        password: ENC[AES256_GCM,data:+HzZmNo+wWmGpLM=,iv:y0FzbI2bAQN7azAQshBWVqJ9hRiAx2FcWYioqbvj/qI=,tag:7KjAyg1y6CRgn+4mGwj5bg==,type:str]
