apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-demo
  namespace: argocd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbVBYRlV0azdLWDJYTm12
        aEVGbVZoZ1FRMzFIWGdnWGNJbEN3anJ1SXkwCjhaTFJNeEVFQkg4Y3VMQ1hvUjcz
        ajdqeTZUaDludmp6cUlTZUVLTWhHaVEKLS0tIGVva1RpZWpsWng5eGFsekIrK1BT
        NlQ5eUkyc21XOVVBcTRQQ3ZONERkejAKUy948WIvj2xRq1VMW37mdQrEpXvCSB6j
        ZJwqWxht+cAJlykPRwHopShbxKTQ9MZL4AWmo31oIyey1PUBfGga7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-10T22:43:26Z"
  mac: ENC[AES256_GCM,data:aLtYg7kMjol5L37xJEaMNJKpj25s7MzZofGLsp0thlPWXhIQmM+RA107iTawsq2LL0F+5Xk3IXRDzLepWqIPEYwZm6mQjoF440IUNasTWxfmp8jO7/Ty/f9WXtnqin+ANFTnCIUaG4JZ73KaaBJGHASXCpTA4Q95GG7NaUUFvzo=,iv:I04RIsYN6QuoDvdWHYMa4PIerZ1k7JNgq+t92VH9Lcc=,tag:WehR+BKGvGWDY0gRLGXN3Q==,type:str]
  pgp:
    - created_at: "2026-02-10T22:43:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA8rRqWJQppmwAQ//Q7WMj4D0i2z9CMRm6aWn1GHarN4ngcljdKr521anZOcQ
        gTGvQ/X/F1tkUzai3K097F5D8jD46IJY9GVzCkXZBt0ykXFApIsuwxV7LiRA94eM
        LPpzZiAhvgrY4zPvG8u3sqU/H8RbXnlENBdO+Fc/qD/tk9NT+Xgm21d/TWp81JOG
        3+riahb25JH6udqWeVM64duL2ourSLlS1OjOH70kTlB94w4LnvAHPd0M9qxBq8mv
        DYzFc323RJeo7cJrGIPds563pi2Bn1Zd90qx6jFwvfQcf49HANlWN4l2TQBTSEco
        s7OoU1NxJF4OPNrJXK7J41oaZqqYu9hwwpZDdS7JDnxrfFgEZ+0Ym52i7mdY0mTI
        pKXsN27Zz//djbRSjZxT1pzC4srAzx3UNAliAzp80C6gzcy12toogjtbab0tAqSJ
        1pBBz5z6PnQkTfDJFZDq/xxjMSGN0r8TGCHAlu9cOPvfcv7jhln7vVTPnqCWmtym
        7HbmaO4IwXAqPWq0r8s2K5DUtR68f9dYE0Gy2jGusnI+iskUs5+GNF1yGEVArVvO
        iiVwV4cH4SZrF8yJNCOcgiUmsd6g0KYUlEHtf5Q0qbdF0NJ81J2DRfsmeVJ7ipnk
        LfnRY1F3rjDBWDI3oy3Ah3u1XlKEaDW7Z+XXFhaERJU/rgwDk20bLQ+pANrm/GLS
        XgHCqTPnsidJEy5BM6uJVMTcDIltHB7Ix9xWIf88PvhKLPYU8Hy5Iy5Z4nYbnSz0
        80gX4xI5Mt8oC+tG/4k+Ve6yKRGjJ1eAOHAwEWbwk1xP1gUqK2RlwoAYku+XV78=
        =NH28
        -----END PGP MESSAGE-----
      fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
    - name: argo-demo
      stringData:
        password: ENC[AES256_GCM,data:mCpmcB10l4ahbRQ=,iv:pq7OsIEl/JFE2paoYrCb6GtbZ4QQw59RCwwHJ+GzsMI=,tag:8qCZo5DuiigXyu4O7+ThEg==,type:str]
