apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argo-demo
  namespace: argocd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYmo1Mzk5ZlNoWTB4Y0xW
        UWQrWDM2Nm5Rb095T1k3eUVxSjVISW4zRkgwCkUxVXBBR1FjckFzM0dyL3hCV1A0
        M1FManZzSlFxalEzUEhzTGhhbFkzTkUKLS0tIDEwTXNiZ3duaER3Z0ZiMFZmZnZ6
        enFqc0FLK2IzaFdzMnVicHErNURSKzQKnD9uFpZqbtegtFJU1O5HreXzIRBYz2FD
        7AlAHjbnoO3firDaPcbMRO/u0e0DhOiS6Jo7E2B/ERXYIcRgwn7p5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-12T00:57:25Z"
  mac: ENC[AES256_GCM,data:lsIsrYyoaWj2MXDcfGpxKptNTG5odPKeaJK/AFRsb/UHbm085HuVLVIsOI5V5iRLnAtXNtnMOfY3HIkrzxmeeTciqn1mKNnwvDABKH+9yUg3fj8buhWjk/opSIV3Omz2VKeIm0AwsHcI9mutUX+DkvSz0/Ov5eqGvT4YJshaBjM=,iv:qCImnfgp7ikh3vFhjnlRnwx34XL9wNE2ifhiGcRZ76w=,tag:MnNqI5sXuXTDoAumsgXzVg==,type:str]
  pgp:
    - created_at: "2026-02-12T00:57:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA8rRqWJQppmwAQ/9H+Co433q9LjrRwbtbbdZ0yO0JLfDFMUvcSSUbMAIqV8f
        WALqHMCWSVcKeaF016+p9C+tYpGi7WF63G4EZe2fD9fh2yXg2Ze3yAilvkd216EW
        ve3Zr3ZAlvAHErxAIPK26LskMVt4h1vQOFbmVpT097PkZh8r55whgvtwv6JoqW3I
        TMJ1VYhCSi2n2TZdkCp2Jxc1L9i7guPEXMxVsTrZ/osjzjvOG61ZhtTIBbIZB2tV
        Jm4YMyKKkcURbBmcCnSjTbiRHlqFrhx3c+0kCol2KVp4+LzrFTWpJsxkMIy2rLrG
        ASYGkbjEvTFw7/ishC6xF96TrIBv2X9Wi3/Cp7GiolAYxKd0STjSC9S1e8yAo0Oy
        uCst0rM+s8XVeHFu898mg6erX4r9fAF8AkQPYtn14pqViHIBo9zT/Q1DuliBZolt
        HVt84jKja67ksFuFp9wh02Sk8RKEEoPxhUA7j0w+0f/rIsusXHae716eNO1zzC0T
        vgRfIJvo1ODpiXeIbYWL5zWerNS+rBEOx2uL63ed80x8Ybe4M35f9SE5ZNfy/3RY
        OM0oEXEN0tbTRCFThSeWOIwRKZoF8yJ0KAR/uLGiMJRAiDX8xZQYl2/l19YZO3KW
        gTK1u26zyoZ80UzCizqqMYqODA1AHCs+fJ/zV4lVmUZ/OAvww9mN7faYPm59mv/S
        XAHg2EFAwzy254sF0/lWao4Acq/lDxYl6QuwiNBOGBUciT/7tv4oIsd8FD5Lv8WH
        PSu/TTZbkq5eidz8EIC72FVZbrB43dM7VmjTAhX83Vc3uH1tzjYqBjI//sCE
        =5++j
        -----END PGP MESSAGE-----
      fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
    - name: argo-demo
      stringData:
        password: ENC[AES256_GCM,data:XSoOMJG0F4z6FHI=,iv:egxRIulzmrN4I4ojHee3eJQQlAfFPqeT50pR4BZtSfc=,tag:nvwujfQauF3NAGw2zRszcA==,type:str]
