apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 2ea2efbda160d2bf582f7bc2db47b1ab3668fe3b7209252790ef20f6ba916e0f
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXppbXNjdUxoNkhra3d2

      Vy9odTNHdCtRbDd3aWMyWmx5Ykc4UUFVekQwCkdQc2U5YjVaNXFpQlFkU2tvNTh5

      SXlBNENPMVJMeHpZN05udE5aWGlLRWMKLS0tIEU3NUFxbHFTYjloVWJHVGFaYjhV

      bTcxQ2VnSGgxS1pZQUxiMVgvc1pYSG8K1/N4Fyf02qmnSPD98G8qp1FPYk+k6dvR

      aWI2kT9vwx7E8Y9BHr9RWfWXijD2sw515xN3WkjrjNyUsIYNvB7Pag==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T03:12:09Z'
  mac: ENC[AES256_GCM,data:Qi+vP0GGdEghS50nMzuGV4U4NTa9MKaeU4aNgXpGSNDIXTxBbDtZJRNGeT1a62neU0wg05UkI0bP+QrbZdEqVW/I5fTyxunh1Hp2hjZbvPS9Nk+JMn7t92HVShJ7UpbI4/50brWYOkD/LQZd1qPl1GMfLN3y8HiJoW6LhzUXEOE=,iv:9vwWE7nrAEMvq1Jen4lIVoEdvucWRLcbFo2qpg/SSiU=,tag:zT7mSOVDSLDHnsiHmfOdTw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-notifications-secret
    type: Opaque
