apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 8c6562bbbbda2fdf03f309c2b6c6a514a96f8f6ee93e969eac3bc155e0793646
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y2VVQmRmNXdzQlRDR1o3

      ejFGdlN4MlorelgzUUlYY29DbWxjUWhCUUY4ClBUcS9LUTVnZGVkMVg1d3N3dGxx

      QnRDV3FycnQzRWp2VFRzcVJDK1RRdGsKLS0tIGx2VTBrMHkzQ2x5M2ppYVhSMzVz

      UXV4RzgrdzQ2ZzRYbXhkYklmL1AxZU0KFAUdwB0+eVr6QcXRaWOP7XUNAae4YQVs

      9yUZRcaw6Zsa/4lrjZ0RD/ZCiwamwxS+8pnPCHLukcEWTTQy8irs5g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T00:55:29Z'
  mac: ENC[AES256_GCM,data:BkZ/+aM2YXtsaBrWxa+ZujP25CAaX7W0ZtQxdOPiY2ypDJpL+hpxKIUW1f5uUQAgXmCcLYy0a253Ur28t7djyvhiqe5+lXxuHokaERQzrNA+2p8mLNeC+h+qcDnroQeanePpHZuCAHxjgIIQHXa++Th7RW3T/v5tsjoiI1ZrTlw=,iv:nuZN2GhUIg/97NXqlBIyqMDnpTT8IOTd8arMEUKyePk=,tag:jwsPq7ScIp4D9luvFhiCKQ==,type:str]
  pgp:
  - created_at: '2026-02-19T00:55:29Z'
    enc: '-----BEGIN PGP MESSAGE-----


      hQIMAwAAAAAAAAAAAQ//cHdFm0UZ4AzxHUlccfABmO1iZUGSWV0z4IwV7U4O9xE/

      UhX6b+VMZTbecrDmac/zNb0x4xdSKYqg9iUKCzSTxQDcOR8FdP142COC0QMMdASy

      +qXcWccc1ES3gV1qWw5JLoHq375wZi7ktKvN8LAuaPScm4J9J+C8m4Y0Ur2SDcFp

      1hC2JaWgWNJ3EUgluRFSQjQ7RW9Nk7KSCTNHOQfM+IN6Vh9tVGFxS6Ou/a3ThdRQ

      Cm6SRMy7J75nUTBQIHMWpzuVHxUt4J+nUqsaISXmLKqt4Y7NzIXv8tF8lUd8xRcp

      5WcjFievclFqSsX77RK3iV4c+jk5SQhigVVDuBBn0eMyVZStA5VxNGHzYcDYn29j

      hf6q0VLqodsYPxrABBLTqldTtYkZkZiy0Bznm2Z3L8A30wfNxo6PF23uv3qHbhCI

      nLCDVu/yHF75Bg8v6K6NQ2Mr894WGQaVnt7Gm0p22ulu89Rjvf6EfMBwnZkz3zga

      Dfo28NPzaYrgZ7Qzz/y9KNd/xaOHk1OHSgN/NBM9gCZvbRA5Sn7tk24N4Neo1dj6

      v3WVLGFpOidfIPQ5PGmTqTopGW+0SGAe6gah5F7fci1aUSMrEZD+8NHpVA0cOX06

      RZ5dqu24E2s3A50QCeb3WJZa4FtexRqvceHTxoao1HLK4om0n4sYiBqYX1mGfqvS

      XgFNCFm6hTWrHV0bT4BVojMBG5pmgGIV9h492c15DDMCiwfuh9AYuCFXACA4kJI/

      r/OcFyeGoq4jjaSY12JLAxCxHLa3tz/vWDKJNQIrnVar4H8/vB9ftf1wX6RdaGI=

      =wlaq

      -----END PGP MESSAGE-----'
    fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:OshVWuo8klXq6xBN6dQmJ+rD0IU3jO/3hb6lKj3d,iv:Qg3kqz7DE0pXI10BV75ZjGUYvcoE+5FJRLQOJqgnCTg=,tag:mZcQqsfLe+qWRReA01UJxw==,type:str]
    type: Opaque
