apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 4d4dd1a2a0ff8a88b4d49e93e4fee2d87e7b68431f6391b495d2c0056f0716bb
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZi9iM3d2MHB3R2FiWDUv

      S0xFeDJQV0tYMTZ0NzlmS0JTZmZqenJMMjJBCnM5amtYd2dyUzZONjFFY29lU05y

      R0ZuZkZUMVV3Y01EOGxuU3JRdW0reGcKLS0tIGdSbVFWbnBlL2QvQlJSMWhzR3Rk

      eWhQVmtxTmZFeG0xd091Y0N3bGJQSVEKbiKfTbtVoF3IJ9dEvY3+7LAvhE6N8SF3

      UWHI0hB2lTCEnwfLHm6j/3R94PwMt4ZoH5kmI2w5TuEk/lCa9k7dOg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:11:54Z'
  mac: ENC[AES256_GCM,data:RpUMZsPfOZ+i1A6+Irl0I7o9pMwKSmMTgwvRzDoGnyOsC2ZGTUvea7NAK0T77XjjGH0QZk51vnI5fqfv68kYfS979AYDQ8egClAmbgIy+1R+B+Zdt6UnPn7eAzpH7QQ721DXIx3OmJf3xvqzEGjOxk59onTCg/XOjH2NqQeD/es=,iv:jnY8TRNrdzuKNAPxXPEhPHqK+H5GKc3TWiQ+/NSKpbg=,tag:wksfn35XfXUkbQM4FUu6qw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:PwBrpxnW3HuOe6W2FfCpnAaiPgTFM4z0uYk=,iv:XEoqA6s7sQ5MSJWCTP2V0qRr7h/ydtFqNRPNu02PcxE=,tag:MgXSAyESuaqRHU/PVZm1LA==,type:str]
    type: Opaque
