apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 41b4e5f54c0c13ab7e02b3895756f250d25aeab11e91c8b9132854e168b92d7f
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbVVYOHZtcVM3bnFLdEV3

      QWpSeXVIUVBDNWJEcHFpaEFhNzhnZnYzYlI4Cko3Q2hKOW1ra2toUm0xUEJuUXl6

      U1RveXdRNlV3b2FETkFBNUMycUZOYTQKLS0tIDB0YTRFM2tlUjRxLytnZ09IczNk

      UEtobTNQTVlWWE9QQS80cm81S2Z6YWsKzzVjISqBMCHByLfwe1NF+IUkyJwebNaT

      dr63UpbdhM/S5qtPnu+dxmoKbnw/ffphb4bFe4RmNrMrVunpuk2RlQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:11:55Z'
  mac: ENC[AES256_GCM,data:Yub+d5C3spKOov9VFKbnx2oWxWwyq/lELUonNYt3PFl87YQS+9cR5EzhtPtaao5Dopo6JHbfTt63ppYFqvmNGgLIB+IIpVcrwP7wMuYiQRhpi6/pbzHHfodnypDUNjTBTblEsTVXMf7f92exKHbqou1dzB6botJcuJOutfq5Qio=,iv:BIqgDE2CKFpiuU2mv8kfKephYGTSntt4sFpPn2vyH6g=,tag:DV31S12838tjxdVzSyDUKg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:Bhg2YLUB/MgT1xD3aS3Qkatfh9rbhZ6Etlr22NLB561qq3OVXDkFd0LZTaSzjyLYmEsWuJwp+ynzBjsz,iv:e5Uwb9fIqYC0I9gJH3gQAue7fgNlw4dhSErhn3Dz6zg=,tag:oLbq8kmkAD5EVgZlKhW8Mg==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:TwTRPsTZN4iwxHz0Z+HV78oa/Z2S3A==,iv:CKQwBUaIm87RUxELUdx9ICGnwZ1pNmjR7kgYBc0ibfw=,tag:gQRZe2WC6PGxpIzuOPCNww==,type:str]
    type: Opaque
