apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 4d4dd1a2a0ff8a88b4d49e93e4fee2d87e7b68431f6391b495d2c0056f0716bb
  name: argocd-redis
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ1JYY21rTktyMW9Hd211

      cGptWjVPT1RsRU9SeWdoZWRJZ2ZqL1F5Y25jCi83Q0xOc3ZsOTZXR0QvaE1MSEZE

      ZEV2NkwrWncyUnY4NGNCbmNmYVZlVkkKLS0tIHE5TmZEMkNDN3BTbmpObzQ2dmpw

      SmpLNk1TblFpT0l6M1FNc3p1TXpWOFkKXfvhA/zu5UVd84/8JKZDQwpDPoJQdi7w

      uEOf8i+e3vf3Y6N+kGD8NPpwWsE9ORRe3tJtMPGrjMzjTriDt35NIg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T00:55:26Z'
  mac: ENC[AES256_GCM,data:/YR5Nz+Xs+rdRE7OXrXr+FnUy64YMC4U2dKwPIwUAP4YUMPKzDnIidDK8P+8c7NHwR7F2foGEk+drrLdoFX8At3P195U3Oj5g/FGssnpysh0bGfKe1n+UsWir7Z9vqgkMVI8/lxTdKy0jw4P4vwiinbG7IYv9orplQEZBPHxhwU=,iv:j9ZfZZtpXd4EIBsD1EVwv0PiP10skjr3aTR38nBhKDs=,tag:SZcG21SSWfFZFroPmdRS3w==,type:str]
  pgp:
  - created_at: '2026-02-19T00:55:26Z'
    enc: '-----BEGIN PGP MESSAGE-----


      hQIMAwAAAAAAAAAAARAAiBGBCbDpYXvlqNWFOwVHQimpSHkSphTgxuYyjmcKyLuW

      kHfwtMamu8AvX1MUt3ZACOMF4jR/YRXJLtJd2raTMDatKytAuVnKrhbOP7waWmfs

      SA8fjvSCfAQ0GVZVYwgY4RXgoURfC4P7QzppbYOaCRMV5WBHcTXbGMppAOoXzcLR

      05aBMKcdhsRUoF2nJcLX9uXPJEPGOfoNn6q5fOsSzWqm2wvbp8ALu6Q7wTD+YD5K

      Fwrt5vLTBjI9R1rzuZ5+ASAaSxLslXduLcyDkboe+ttWTLoktCJAQZG99KLjsU9b

      no3L1/tMkEAQZ4htEilPmVhCVID4v1zMW47pqk9u3YUUB8oYM4rbcGdVKHVpt1wj

      VZXXmDNN+8iRSb/CxWg4P4CN+CgJjWomyQz6x2tjOhWctR4Z26b9bQEI3CPTtl5m

      jVqrg+wnjYOxfSN+QBbX2/lyyohK4PGN3pzkoIKAuzEbN4L5MQ3kAIQ6hlDHgBuL

      LsfXtqp3XcS5709w8nyII13UL5l4J09TYie/TTWy6fc1/pSVujpxoqwmMPTwmOQW

      4whNJZiypWEH4ZlabFmXhQBPRFkBbsVVlnD41A+rPNe2AxBq4OAm04pWO4Qe/kZe

      J98iM5F+EEaLDLCRGowDN6NULYgIinUNfuoJk6WnmvbSXzbaK4M09WAnjexXjxTS

      XgHzgJUDuLQn2CjwodcWSQDBTox0S1ILrrTm3tF/F/GUDirdYdHJhEIgFelFymjF

      YuRdgnO5Yg92EYAmofmwAY1eZ9B+vr7qfXKbX/x2hqfMl0yS1FIfyoxmMvPRIvw=

      =Lhv9

      -----END PGP MESSAGE-----'
    fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-redis
    stringData:
      auth: ENC[AES256_GCM,data:FjAn0DeDKxhS0ls3GaCbB5RsvGOXZq75qkc=,iv:6qIx3KoHASf8olUZ9HyASpkfeNUb1eheHx+QKytGZo8=,tag:8BI+IuBXEoCwm8D/hJPK9g==,type:str]
    type: Opaque
