apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: e9fef41cb099fd0e43dfee26ea679304f31c68a826a4fbbd12652321404bc326
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQURqZGtIQXlUbW1zNDQ0

      dDl3MkZLQk1WYmF4NWpuT3p2L2xjZHlnMVhVCnVOK3FtOHU2M1Z3Z1Ntc2lFOGgw

      NHBkL214Z1krdS9XQWgxVUFNYUFpMFEKLS0tIDdxWHMvTi9PK2F1YlFjb2p6N2d5

      Q0g4YXo2ZTFSeWFWbTVIdE5FMk0xSHcKWWy9AoD4FcRgS3fMoX/p/jeWkwGeiNE6

      eernqLmDhl2GzTYNFX+tMrfxacWfP5lfqZcQX3VV7j4pOeqmbzH+Iw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:50:46Z'
  mac: ENC[AES256_GCM,data:IvqBkBYJSGI1Fif8YdHwC5bb/PqIPzQsnSlQ1f3fW3eMGxm6Atf8QIXqz+T3tuaWafSkKR9XcL/FmPJYN8JshAPj75Fc0K9OpqM9IwyvJ8oFvof0CYq5fOYZ72ep4TMzRk3EDjsnE7HZ7lqrjXyXmJN53uDvy1jC5FNDfLa8NRM=,iv:SMVONgf84x3oigggkza6HkEV1tGDALflN6NnIhN0HQ8=,tag:U301oI1DmWDCcV2fmHo+nQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:v8wVskDXHbYifzrdsOn8QQBM/DzQTcGL0qnK5imA4q7CYhVNLBnY7mHTYgEtx4qAwZy23S578SJ6Br15,iv:wD5bPSX3FGasZQnJEj3bW1RGTAHN0CWpIrAOO8PS4Kc=,tag:YW31IRKCWcuE7zUPFybQfg==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:hJBg5JmFtI8zmuDCjhvJoBiFqM6yjA==,iv:1ks0ve0KEotN4IQZJ9xSQofwHf0ogtQGhEXa5VOMiKY=,tag:UcM4pax5EnLY9E8fEfjO6A==,type:str]
      server.secretkey: ENC[AES256_GCM,data:V4rfdbt66KdZnHVtUXrZdp9hfFpSr+7hUCL0NI9f8ih+GTH67/5fTS9DboM=,iv:1IzG+7ywGzB5/Tb/NZRSD/ligizaGdcWRSEm74pGPhs=,tag:8a7RCxBsOJU96jcHP+o/sg==,type:str]
    type: Opaque
