apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 41b4e5f54c0c13ab7e02b3895756f250d25aeab11e91c8b9132854e168b92d7f
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV0V4UzVkaDlLM3ZNSkdj

      a1BTazJ1M21sVEhKa0Q3by9GazJrQWkydjJrClBLYkR4OFlReE9ka0tTM0wvNEpm

      ZUpjb0pQZEZOMXRrY2MyWDljSHVrNlkKLS0tIENtZ25hNVh2L2k3cVMxMFFzOTFt

      SmNPaGN0dStGV2RnMTRjRStqU0NuRzAKecxgtJyxEoVgjKbNwRynShUgu1jHaCzM

      Guez9/qVv0rqFRk7VFa7wv+0IHQUOyvXaYDL+WwVnPj/DyXifc7gAw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T00:49:31Z'
  mac: ENC[AES256_GCM,data:UcTxBu99Y7jjYUWTGy3ef2oPWYSehtjiR8x7K7nFfqMCMDcAfQZC5sN1KY5BcdnQIeBF/SQztkbAU6irkajw0123S2YEV0KkkblHPmd5BTbP5lMtacnaQ/WVY7sktHeiz4ZvSVAM8yUZJyabZCF0TUOsJ+/iqla8wo8skQfqwM8=,iv:6I5WA+jQQ11E6Ud9V47pfxXSRLzE2wunDhxkoV/sPt0=,tag:pDEsTkhH3lazQ75wCY9TrQ==,type:str]
  pgp:
  - created_at: '2026-02-19T00:49:31Z'
    enc: '-----BEGIN PGP MESSAGE-----


      hQIMAwAAAAAAAAAAAQ//TJe/1auevnetHpi64ZvxpXfj+nVhQSd+J0XwJmm2OqCL

      AgYrYiLfB8+dvvqEP5FQiInI303l/NWNJL+hxaCQobjLm1CviP936L4sKQmmM9bC

      h/i/oFCPW0yui0tzHepT5RmyTqqjss+6L+ewQcYtjUxJfCUfSQNxvQoxPynmW7Lz

      PfTJEjBaFm4mBUxYjGAKjoQ8b5yzuFp4Y55nEeuksBi90gwC+Zi1N0Pt+AWwTsdF

      v0DzBpoT8X0FZF4iJmehn5piMNsMkT2wSXD1SQUf94b7Y3xroAJOlBZV11H/jQ25

      W8p4VVjGIM2AXv1hOC9+bn6AO1lY/QG3O+jjpYGmuumgsrOFQys0kvVsgGOuY8vi

      JOwQoxfQgFwfsjND1/Ff+nFr0THvI+5y7+W6xdCmAiijnMDgGnmzLepc18iRdGAP

      UjdjGnQC/jNoTwtCq39Z38pEHtWs66nJaZJkde4HLjipIXfUxtpDZH3zsLA3h2xi

      YzXLolNfxF2a1feHYFFcDYEYHH/ALKdJ8R2+VtTiNxGcCx3nlZ6qM4bQVC6Td5Dw

      MaFB2MhQ38Jv8ulrUlufzOcT6SizAc1LZT5RDIg3YLi4EDstgYTcV0y9DL6vj9dV

      OeGro+N2euSQ6YG9xtb6pknh8CqFVzliHlu3g6XphGbkjaEmk7hTvHAM0kZxIhnS

      XgEZ+KKywc+IwE72MwzyIqBSd972dmcTYR58yAdRQgfvaIO8MshUHDyxmWzb/xOR

      FZ6fD3287A2mpGMY9OjKVxsn5Iv3JvMnJKKxzAq80YpNXK236DOiRoaz7atfm0g=

      =cpu0

      -----END PGP MESSAGE-----'
    fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-secret
    stringData:
      admin.password: ENC[AES256_GCM,data:FENkRaERuNupeG9+cxa4A219RvoVjETZS0Y1QU8aAy8rxJ390YZSQay+f38N8Lje7nxi55Bv3Lk1b8g4,iv:B2FZM1d+v5lIgqD2qWoNZ6X41Dax1cCpkwuMYaQ2xuU=,tag:ESFUyYdy1FglO2o3NShofw==,type:str]
      admin.passwordMtime: ENC[AES256_GCM,data:X+tRpLvEFhOSJ2WS42QUCEE0/gD3ag==,iv:vjeyvm/DH+30VWam/gpottv9Y3NfqlUUHGQZx3jmvjc=,tag:Xs7aq20EgKVFYORhD16lvQ==,type:str]
    type: Opaque
