apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 2ea2efbda160d2bf582f7bc2db47b1ab3668fe3b7209252790ef20f6ba916e0f
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-secret
  namespace: argocd
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU0ZIS1dqSVBUUzREcnFn

      cmRKTWtQMnpNWXA4eDdMZFBhZDhrNDE1L0RJClk3clF1YUtMZnY3dVg1dmRDMmZx

      SlFDZUw0cG1lREpTckZIcTh3R3p6cTgKLS0tIFUzMU5ReTlZcFEyNlQwVDlaMmx1

      QWhWQVUxMmhuLzEvdjhxSW1lYVpPUFkKP7gweJfDXnSrsXbNAjEyfG7PVmAej1+N

      OzGkaX3jmE/Aisnyy0DNH8uK9lhf/cSsDPz/uNT69hZF0+S9sng9QQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T03:12:06Z'
  mac: ENC[AES256_GCM,data:x+S1BwsZdBMhZbFGgY8+jXlLiQFjrjUtQ2Drou3EVruUPhbuxUx6TqmoFT3BdFxAInrDDtlWukezqN8GG234F8mX30IlxolBcBXnV8F7Iw8dj4wAkIjW/Zq+QYWPWPXI1b2hYeadyDrp6WHdU6kvILjur1mE6+zdKb+Ihrm62vA=,iv:ri3vxkko3Vg/p0ru5SY/S+r4zAMUjn7EuQSNtd588hQ=,tag:B10F11O8CMk5/kqzD9WkrQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: argocd-notifications-secret
    type: Opaque
