apiVersion: v1
data:
  passinit.sql: |
    ALTER USER root@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("PLACEHOLDERROOTPASSWORD");
    ALTER USER romm@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("PLACEHOLDERPASSWORD");
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  labels:
    app: mariadb-17.11.16
    app.kubernetes.io/instance: romm
    app.kubernetes.io/name: mariadb
    helm-revision: "1"
    release: romm
  name: romm-mariadb-passinit
  namespace: romm
