apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: romm-14.27.4
    app.kubernetes.io/instance: romm
    app.kubernetes.io/name: romm
    helm-revision: "1"
    release: romm
  name: romm
  namespace: romm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: romm
      app.kubernetes.io/name: romm
      pod.name: main
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/cnpg: fc940fff4269c53072f7039f0811133e9b83400670af014010bf50d3f13740f4
        checksum/configmaps: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        checksum/mariadb: 582124f15391d12ea715ee4b5f4f2636d6cde2a96650d4dff21346e846d74246
        checksum/mongodb: 09c85576cb45b1eecd1467732b11ea8fa3363b0105c465f02a6ad64991521d52
        checksum/persistence: 93f297b2dc801369910048359b61f369b9fa6ef724d690f7364d70cf9aeb0073
        checksum/redis: 4d1bb1dd0b5adf09a380822068e73255eb13cb1813e88ae6a4484184bb96ef41
        checksum/secrets: 57bf320e00fad4536a3dd9c558f037ed68e472dce105e95a15379d138b20c992
        checksum/services: 4b546be00d25ad56b44b4d24cbff97d9830c9d79b2a43912df4e5912c109bf16
        checksum/solr: 29c14feeaddbf7762052db593898d274941f539cee681ddc613957587686f347
      labels:
        app: romm-14.27.4
        app.kubernetes.io/instance: romm
        app.kubernetes.io/name: romm
        helm-revision: "1"
        pod.lifecycle: permanent
        pod.name: main
        release: romm
        truecharts.org/pvc: assets_config_resources
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: truecharts.org/pvc
                    operator: In
                    values:
                      - assets_config_resources
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TZ
              value: UTC
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: plainhost
                  name: romm-mariadbcreds
            - name: DB_NAME
              value: romm
            - name: DB_PASSWD
              value: PLACEHOLDERPASSWORD
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: romm
            - name: DISABLE_CSRF_PROTECTION
              value: "true"
            - name: HASHEOUS_API_ENABLED
              value: "true"
            - name: HLTB_API_ENABLED
              value: "true"
            - name: IGDB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: IGDB_CLIENT_ID
                  name: romm-secrets
            - name: IGDB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: IGDB_CLIENT_SECRET
                  name: romm-secrets
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OIDC_CLIENT_ID
                  name: romm-secrets
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OIDC_CLIENT_SECRET
                  name: romm-secrets
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_PROVIDER
              valueFrom:
                secretKeyRef:
                  key: OIDC_PROVIDER
                  name: romm-secrets
            - name: OIDC_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: OIDC_REDIRECT_URI
                  name: romm-secrets
            - name: OIDC_SERVER_APPLICATION_URL
              valueFrom:
                secretKeyRef:
                  key: OIDC_SERVER_APPLICATION_URL
                  name: romm-secrets
            - name: PLAYMATCH_API_ENABLED
              value: "true"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: plainhost
                  name: romm-rediscreds
            - name: REDIS_PASSWORD
              value: PLACEHOLDERPASSWORD
            - name: REDIS_PORT
              value: "6379"
            - name: ROMM_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: ROMM_AUTH_SECRET_KEY
                  name: romm-secrets
            - name: ROMM_BASE_PATH
              value: /romm
            - name: ROMM_HOST
              value: localhost
          image: ghcr.io/rommapp/romm:4.6.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 12
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          name: romm
          ports:
            - containerPort: 8080
              name: main
              protocol: TCP
          readinessProbe:
            failureThreshold: 4
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1500m
              memory: 2400Mi
            requests:
              cpu: 75m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: []
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1002
            runAsNonRoot: true
            runAsUser: 1002
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: /romm/assets
              name: assets
              readOnly: false
            - mountPath: /romm/config
              name: config
              readOnly: false
            - mountPath: /dev/shm
              name: devshm
              readOnly: false
            - mountPath: /romm/library
              name: library
              readOnly: false
            - mountPath: /romm/resources
              name: resources
              readOnly: false
            - mountPath: /shared
              name: shared
              readOnly: false
            - mountPath: /tmp
              name: tmp
              readOnly: false
            - mountPath: /var/logs
              name: varlogs
              readOnly: false
            - mountPath: /var/run
              name: varrun
              readOnly: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      hostUsers: true
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |-
              /bin/bash <<'EOF'
              echo "Executing DB waits..."
              until
                mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" ping \
                && mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" status;
                do sleep 2;
              done
              EOF
          env:
            - name: TZ
              value: UTC
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: MARIADB_HOST
              valueFrom:
                secretKeyRef:
                  key: plainhost
                  name: romm-mariadbcreds
            - name: MARIADB_ROOT_PASSWORD
              value: PLACEHOLDERROOTPASSWORD
          image: oci.trueforge.org/containerforge/mariadb-client:1.1.0@sha256:67e74083d952ab67a31a6adbf43ef429889b9ef084a5583b0c939a892d3b1b9b
          imagePullPolicy: IfNotPresent
          name: romm-system-mariadb-wait
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: []
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: /dev/shm
              name: devshm
              readOnly: false
            - mountPath: /shared
              name: shared
              readOnly: false
            - mountPath: /tmp
              name: tmp
              readOnly: false
            - mountPath: /var/logs
              name: varlogs
              readOnly: false
            - mountPath: /var/run
              name: varrun
              readOnly: false
        - command:
            - /bin/sh
            - -c
            - |-
              /bin/bash <<'EOF'
              echo "Executing DB waits..."
              [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD";
              export LIVE=false;
              until "$LIVE";
              do
                response=$(
                    timeout -s 3 2 \
                    valkey-cli \
                      -h "$REDIS_HOST" \
                      -p "$REDIS_PORT" \
                      ping
                  )
                if [ "$response" == "PONG" ] || [ "$response" == "LOADING Redis is loading the dataset in memory" ]; then
                  LIVE=true
                  echo "$response"
                  echo "Redis Responded, ending initcontainer and starting main container(s)..."
                else
                  echo "$response"
                  echo "Redis not responding... Sleeping for 10 sec..."
                  sleep 10
                fi;
              done
              EOF
          env:
            - name: TZ
              value: UTC
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: plainhost
                  name: romm-rediscreds
            - name: REDIS_PASSWORD
              value: PLACEHOLDERPASSWORD
            - name: REDIS_PORT
              value: "6379"
          image: oci.trueforge.org/containerforge/valkey-tools:1.1.0@sha256:ff58ea59c54d579152516df543f0e4ae42294f05e24d7f4d54f80000085fa571
          imagePullPolicy: IfNotPresent
          name: romm-system-redis-wait
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: []
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: /dev/shm
              name: devshm
              readOnly: false
            - mountPath: /shared
              name: shared
              readOnly: false
            - mountPath: /tmp
              name: tmp
              readOnly: false
            - mountPath: /var/logs
              name: varlogs
              readOnly: false
            - mountPath: /var/run
              name: varrun
              readOnly: false
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 568
        sysctls: []
      serviceAccountName: default
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 60
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: romm
              app.kubernetes.io/name: romm
              pod.name: main
          maxSkew: 1
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 2400Mi
          name: devshm
        - emptyDir: {}
          name: shared
        - emptyDir:
            medium: Memory
            sizeLimit: 2400Mi
          name: tmp
        - emptyDir:
            medium: Memory
            sizeLimit: 2400Mi
          name: varlogs
        - emptyDir:
            medium: Memory
            sizeLimit: 2400Mi
          name: varrun
        - name: library
          nfs:
            path: /r2d2_0/media/Roms
            server: 100.117.238.67
        - name: assets
          persistentVolumeClaim:
            claimName: romm-assets
        - name: config
          persistentVolumeClaim:
            claimName: romm-config
        - name: resources
          persistentVolumeClaim:
            claimName: romm-resources
