apiVersion: v1
kind: Secret
metadata:
  labels:
    app: romm-14.27.4
    app.kubernetes.io/instance: romm
    app.kubernetes.io/name: romm
    helm-revision: "1"
    release: romm
  name: romm-romm-secrets
  namespace: romm
stringData:
  ROMM_AUTH_SECRET_KEY: JWcmc9NWx1R4opxaaBxFYG3BJ2w1YcfnI8mVRUc4SYnJrhYiSONxurm6Q0n8JpRq
type: Opaque
