apiVersion: v1
kind: Secret
metadata:
  labels:
    app: romm-14.27.4
    app.kubernetes.io/instance: romm
    app.kubernetes.io/name: romm
    helm-revision: "1"
    release: romm
  name: romm-mariadbcreds
  namespace: romm
stringData:
  jdbc: jdbc:sqlserver://romm-mariadb:3306/romm
  jdbc-mariadb: jdbc:mariadb://romm-mariadb:3306/romm
  jdbc-mysql: jdbc:mysql://romm-mariadb:3306/romm
  mariadb-password: PLACEHOLDERPASSWORD
  mariadb-root-password: PLACEHOLDERROOTPASSWORD
  plainhost: romm-mariadb
  plainporthost: romm-mariadb:3306
  url: sql://romm:PLACEHOLDERPASSWORD@romm-mariadb:3306/romm
  urlnossl: sql://romm:PLACEHOLDERPASSWORD@romm-mariadb:3306/romm?sslmode=disable
type: Opaque
