apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-02
spec:
  bgpInstances:
    - localASN: 65002
      name: local-frr-instance
      peers:
        - name: local-frr-daemon
          peerASN: 65002
          peerAddress: 172.16.255.2
          peerConfigRef:
            name: local-frr-peer
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-02
