apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: cilium-routes
  name: service-cluster-ips
spec:
  advertisements:
    - advertisementType: Service
      selector:
        matchExpressions:
          - key: service.kubernetes.io/headless
            operator: DoesNotExist
      service:
        addresses:
          - ClusterIP
