apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: local-frr-peer
spec:
  ebgpMultihop: 4
  families:
    - advertisements:
        matchLabels:
          advertise: cilium-routes
      afi: ipv4
      safi: unicast
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 30
    keepAliveTimeSeconds: 10
