apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romm
  namespace: argocd
spec:
  destination:
    namespace: romm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./kubernetes/generated/manifests/prod/romm
    repoURL: https://github.com/sini/nix-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
