apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: f13b9aecc3fa23a29cb7165b3db0b03d42fe6cd58ff29d18440b466c59ebcda0
  name: cloudflare-api-token
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVzBmcEg3VlRDd3ZmTVNh

      TG16RDg1TnFmQ2VZU2RVQ0trbDRkU2VOckNNCmNjdWFKcUt5ZGEwd3ArVzFBellX

      dFpkWlIvYW51TWhMZDF6VU1EeVRsRFUKLS0tIGh5bUJ1bkdOaDJzd3BNczhOUTJm

      TSsxeXh5cEc3RGtxaHRwZjc5aVo0VEUKbVqN3lBOmLH9LDJAdT9ozRKdjBVKenZn

      85u3so0L+MgZimHhD1qVILWUDylhqHuecFu7oDvSnvzyIsDI+YIOUg==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-20T01:33:25Z'
  mac: ENC[AES256_GCM,data:I3MVPCTByGDmTTg4unG+hF9uN0HS7QrCp3SI2gsU4L8P/oNevxahLUflbOc21KbrVddtBCr5IAksck0wkEp/mnKyCWzgPM8AyUE113P4kqK+pm6vp/oyDD1JGvFjlw/5VI9agACL/hu0IcYxlqMVHGLELZoR3qUd+OLS9nqPYxo=,iv:GYhNVD/SetRBHBDY7da+k+FrfRrMNo91dfu3utrc12w=,tag:/cecGPHhnQ8KVksQ3Cx9LQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: cloudflare-api-token
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:uRPf/Ev5OWlp9HTiP8+m5z/m7v4zETuFcepj7IA0/bCvx6R5ovu2ug==,iv:IbneTalGLTF3g5QkF+iNxAFY2P/5FFp3xIt/BPVqUDc=,tag:m5p023lSgFYKAmF0m5JviQ==,type:str]
    type: Opaque
