apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: b44ed5542086cd85666b7faa4ba74554195dfb35e6cd32fed895ebfe3fd73fea
  name: cloudflare-api-token
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNHJqMXd3V3hYR2hmc3Ur

      b0l6eWRhUmRNd0dadnhGNzBMellNdmtjd0I4Cks5VmhRT2lyNjhxbUZsbTcvQ0Jh

      RXYzK3hjWkhyTk16ekZvZHlBamRQZ0UKLS0tIDNmaFhWV1V1S0hTVjZLYVpKY2o2

      RjNLOUtoczd6dkkyTkM2aWhKbjRDYmsKZ+AlpoGHqAk44d86nQYob8UmVQRvBx1c

      5OKdd6NNIqW1qs/hIFSBDdAfB+wVg62M4y0MtVPZohsAal94dSMqsw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T20:25:19Z'
  mac: ENC[AES256_GCM,data:dPXk+LlRYuouEyvK0VJcWy0+xhTtvmHaMcYwVAYMMbUxZzBh8YO0fmNkeO+Vz7slK0/p41w/NcY5Riqf+bFGDV4B2txovEWbBf5XVvc2JBct99ZZ3kszGRqt/qSL3l7evR7hr173PHrLas+ErYJf63mgGa8ncoG6y65G/b9nEzI=,iv:HKl3sSno3JU+YeR4PoHdivVSK5IzXtvZpFptw/Jdsco=,tag:9+fUhMVBfsy9rw55STBoUQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: cloudflare-api-token
    stringData:
      auth: ENC[AES256_GCM,data:oKJ7iCzhyoXRMBshTIviL5kBJy/5xbXDa/TFCiFnkZvnwWtSvH6wYw==,iv:Ox3nBfB9qzm25CyprTVL7eroeT4QtI+Led79z/4oBJE=,tag:7nLQkUb2oiBHh8hKSOa+pg==,type:str]
    type: Opaque
