apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-certs
  namespace: kube-system
spec:
  commonName: '*.prod.hubble-grpc.cilium.io'
  dnsNames:
    - '*.prod.hubble-grpc.cilium.io'
    - '*.mesh.prod.json64.dev'
  duration: 2160h0m0s
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  privateKey:
    rotationPolicy: Always
  secretName: hubble-server-certs
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
