apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-relay-client-certs
  namespace: kube-system
spec:
  commonName: '*.hubble-relay.cilium.io'
  dnsNames:
    - '*.hubble-relay.cilium.io'
  duration: 2160h0m0s
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  privateKey:
    rotationPolicy: Always
  secretName: hubble-relay-client-certs
  usages:
    - signing
    - key encipherment
    - client auth
