apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-03
spec:
  bgpInstances:
    - localASN: 65003
      name: local-frr-instance
      peers:
        - name: local-frr-daemon
          peerASN: 65003
          peerAddress: 10.10.10.4
          peerConfigRef:
            name: local-frr-peer
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-03
