apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hubble-ui-oidc
  namespace: kube-system
spec:
  cors:
    allowOrigins:
      - https://*.json64.dev
  oidc:
    clientID: hubble
    clientSecret:
      name: hubble-oidc-client-secret
    cookieDomain: json64.dev
    logoutPath: /oidc/sign_out
    provider:
      authorizationEndpoint: https://idm.json64.dev/ui/oauth2
      issuer: https://idm.json64.dev/oauth2/openid/hubble
      tokenEndpoint: https://idm.json64.dev/oauth2/token
    redirectURL: https://hubble.json64.dev/oauth2/callback
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble-ui
