apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hubble-ui-oidc
  namespace: kube-system
spec:
  oidc:
    clientID: hubble
    clientSecret:
      name: hubble-oidc-client-secret
    forwardAccessToken: true
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/hubble
    scopes:
      - email
      - openid
      - profile
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble-ui
