apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hubble-ui-oidc
  namespace: kube-system
spec:
  oidc:
    clientID: hubble
    clientSecret:
      name: hubble-oidc-client-secret
    cookieDomain: json64.dev
    forwardAccessToken: true
    logoutPath: /oidc/sign_out
    provider:
      issuer: https://idm.json64.dev/oauth2/openid/hubble
    redirectURL: https://hubble.json64.dev/oauth2/callback
    scopes:
      - openid
      - profile
      - email
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble-ui
