apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: e404f7b06fe24013074b41859fb9f1160b02eb6af3f86e5163f148022dabc82e
  name: kanidm-hubble-oidc
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V2tOL2M2cUM0cmJVUUZv

      TlBUREQ3eEZkYzFuWHZJckRCRERNY0Z5T0FVCkdVcitCMjJEdHhIVmlHNGlaL3Yw

      a1lHZkh1a1k0TmhWempaRy8zNkFsVWcKLS0tIDlqVWp5WjFNOFhlUi92SkM0bjN3

      ZGpwLzlOQXdDUUE5UGtOZzJ6UC9kRmsKwQ58DoBSgqD1fcQ0+L3Cl8O2Xq7Od3Kr

      pZCJcYv02lIGZGbz5Y/or2+YwTAavPN3yQ1tkxKr26Ts0t2PmU367Q==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-26T03:50:17Z'
  mac: ENC[AES256_GCM,data:QesezAAro9d8MaX7UVOaizOBQKcAauj0gPgp+h6U8Aa075SZmohlEW557B5dEJCk0ixBDzUPs9v67BzW8qXRYqh3Cif4zrZwMWCadPyDO0anqIy/+evM9Htn+EGAa6GXBIBzqfUzjZw1QZwjsj1ZTJd8sPzXjohvtxh8SunEXiE=,iv:wbvm2HMg0BpZzzuaWR5bbnw81tAlvnduO5K7penzfho=,tag:XGG1Cq9LipGv6jGEzPL9nQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: kanidm-hubble-oidc
    stringData:
      auth: ENC[AES256_GCM,data:wBM2ZIXsc51g1RSqWlMFOKKL8FBFvjisGhuAuOzDhhsmFci8ic413rPImT+5YxNi4Fk4FqJl1psmwCUw9Zzo/yqnC99j7+CB,iv:QZ/bkxaEvJ76PMWgnOg75zy5P9lEjFy/Uc2WMYDMQWY=,tag:2Eotdfo1xkB5IcntAv/eNg==,type:str]
    type: Opaque
