apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 1f6f734add49983ed5233e1224b1680c073875d2279544bb0ce8c0566a7b601b
  name: kanidm-hubble-oidc
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSkZ6Q3I5UkNZbWRXTm5P

      czEzMjhXNXJ3Q1ZiaDVIN1psUFVWVW55UGxJClJwT1QxbUVxbnR3dlBaWnJ5T0lv

      bzQ2TmhRV0lLQjlnOUw5S1NqSGwwazAKLS0tIHRsNkhrTkgrU2VWOHJieEFsUHdS

      WURYMEJaRnF4aFQwdHlVZU5hZDVPTFkKo4nJV35jdjdYFXDiqXkqojkqordq7h7r

      au9PUey5EjYT3vbXQlrUyBAZcSy00aT3bRBKGiq8agM601v7ls13DQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-26T04:53:50Z'
  mac: ENC[AES256_GCM,data:/vWoXLH21M6aQLyD/kivdBSAzsjZnsz5YQwpW9r8+DGHvZ8Z9mYa0EtxP9M432+8QNNGgVICbR6XcB9NQEBJP4lV7BwV5yOMOUzsSkVaAcEz7MO5DWo+9JIf+JkBf+kUiOluGfV3ReySk1ZvkngW6lBxzUY6HvdAh8rw5dhNKPQ=,iv:PjRgqUqbW5ArBx2W3rXUyHvPfD4QVq1olUcnupsYGkg=,tag:6jeWUrp57u3pk4zZPQqRbA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: kanidm-hubble-oidc
    stringData:
      client-secret: ENC[AES256_GCM,data:spoZU6QCTUK6RQYQpnKMHAKOgeS8VjrAAzmjQpPE5SirAKJwy8FOasQfebNgxxgfbu6M8FjQvEvxQRPWe5laN0JyfEZORdcy,iv:NxeTW2z/pi5yfQ07J7rbkitHmA9buPznGUD6pLrBrSo=,tag:6P60ySH1wmZfXodEvnirBA==,type:str]
    type: Opaque
