apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: e93b5979a7c0fcffafd71ab05e1df034deac291822948e7c5e607194c2a7861c
  name: hubble-oidc-client-secret
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWHFvYmhMbzI3Y1Uzd0hU

      UkZNL2FQR1oyLzJNanpoazYvSllLdnJEQm1zCjJJVWpmeSs1QUd0VXBTL25BUk13

      YW85S0lqMGRtY2tnMkhnU2dFZ2RNbXcKLS0tIHM2QkNuQ0JBSmdaV1VYbnpWc1pD

      eHU0WVRGb1NGS0g4RWRlOE9kemhvT00KWqNiIP3B/CmhwxaMw/jZFsTWMhdZTVWF

      pha2nxhSZaiswejD/4dYnsCQSBEguo6BQ/9O8PZyr4AcU1JQrle5OA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-27T20:48:18Z'
  mac: ENC[AES256_GCM,data:4qdmNdxhiJtzFMJBUxH8aTFMl3vqYA27DrUhkmDcakzZK18ZBO+HUBzZJHBsUJF5nzDrcl3pXcl9CufDBS6nfmsEcIDn41tZ1C/ZN5QuRzJDNXE00IbX5eiHciTBRsYYBKawGXGs+JAkkjH1vz8I8kSuZ9kke1E/F3KAj0OmKxA=,iv:nPhZE8WBMgmEMtJGPUjo1CKHAInTVeCoTvWMGe+yxww=,tag:OXJ4S/Oo4hl/zEuHfDEVZw==,type:str]
  version: 3.12.1
spec:
  secretTemplates:
  - name: hubble-oidc-client-secret
    stringData:
      client-secret: ENC[AES256_GCM,data:m8sj9xh24b2dhpxZ8LBhF0go4VfmvDdur9sbjnUDK+0NTDE1B4aeNn2HaDiYp2eNOptyX/DvqKJ65VfSWyPQcsrZLSs7639o,iv:zIvJFFEFFkX4bvwY6j5FXlWAXDoDUpN5gknjKZBx7Xc=,tag:c1uJBtFdBeEjzC+1SBTOuQ==,type:str]
    type: Opaque
