apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-axon-01
spec:
  bgpInstances:
    - localASN: 65001
      name: local-frr-instance
      peers:
        - name: local-frr-daemon
          peerASN: 65001
          peerAddress: 172.16.255.1
          peerConfigRef:
            name: local-frr-peer
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: axon-01
