apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 10.12.0.1
    lbipam.cilium.io/sharing-key: cilium-ingress
  labels:
    app.kubernetes.io/part-of: cilium
    cilium.io/ingress: "true"
  name: cilium-ingress
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  type: LoadBalancer
