apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: 1f6f734add49983ed5233e1224b1680c073875d2279544bb0ce8c0566a7b601b
  name: kanidm-hubble-oidc
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY1VRdXIxWGdEY3Q3eHh4

      SmlHRW1GdTZ1dHhjZGxUY0E0ejJuTHVkQ204Ci9rQkFYakFjVlFIU0NYT2JuYTBT

      TzZ4aXNtRDBWQ0xiRGQzejZMTnR6TkEKLS0tIHUzaUEzeGFtWmtMZmlNL242Ykxz

      dEtlUWFHRlJIZnI0SE9aVk5Ia1NJRFkKNGPXPXmeEycyv/OtMwgPBVHkRTzbagxZ

      RNz0cbtK1MkQEI3PXvh7CiqDMf2Ul+1/UWExGxFQ6kwvlzDhQMloTw==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-26T04:53:45Z'
  mac: ENC[AES256_GCM,data:ELwCWl0d7OjKKC3ROAyPWe/1+mnJseRd0LekQuF2qLyfhdUd59cTRbHxlGGAkbSid1DKlnrLJEg4SPZH8HFPGexcCj0SLSewd4TYli7Q88rmO0K8MBWzMZ+a85c2m1F2j6/H6Z3qQNE7/992adBPGQCKYFhDngEMCcv7ftTx7C0=,iv:2pe4k0bRyoEVcYlFsWPWtjqR57j4MKB6ug1YfY8vD9A=,tag:J4x/4yfCop9G845fzU47CQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: kanidm-hubble-oidc
    stringData:
      client-secret: ENC[AES256_GCM,data:MFPhIAcJ1WriLlQe0uNgI+sJEwiNl+5i2KRkOm7oopBh57HkkHfQay3NFZmaF2sJil3aRJJpCV0wcacCpaIsH/eOoMZN1Xk7,iv:Cif51E4iu3GwmCuw7QNrv6JTxl64epbf44Z/hrl5gQI=,tag:a1lQao/Xoep30fVmfJ/LYg==,type:str]
    type: Opaque
