apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: e404f7b06fe24013074b41859fb9f1160b02eb6af3f86e5163f148022dabc82e
  name: kanidm-hubble-oidc
  namespace: kube-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c2c1VUE0Q0ZkbnM0dmVR

      aHdaWW4ycjFHdlVzVm1xejBBRGl0WGQ5MFZVCno2N215MElXZk5PWk5wbVdwWFVv

      OEE0VURpWU53SXNpME8vK2J2dkdSTVEKLS0tIFh5WVIva2JleWxMUjFTa0Z6M0NQ

      QUJtelFBK08vUXpMZ0JHTzdaaEpiWFUKOu87GdPl+w7IuTasdx6r/5UJNd0FOok2

      yxF3saHHKqHFgOSan36Lvlr0TcjfO650TlY03FHMIq3vz72xnCImSQ==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1v9fv8xdeektkl6uanpttlcw8qt4c37rhy4hkm63cyg4emzz5rfkqfdgffc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-26T03:50:12Z'
  mac: ENC[AES256_GCM,data:QQ3kCC7A7lOMNwS47ZbHA4wkv2tuUDLiFgnGsw6Od8mrsQvsoyI3dYQHsUibyZaOUsKieSKlq/gaKXCGfa3IzsWTksW3/G95l/Cvu7Ezq1W27qNU5zF7sPVLU9aKKIfhp13NSCYg+ezrcsrqR19QBccePpK+VN2TtJqLuo7Ozgo=,iv:0s0iIGJGPst/qBnXcjwgu//nd4r2VYPHlolxqyc520I=,tag:FMhNsytnCSAAfP4542CuaA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: kanidm-hubble-oidc
    stringData:
      auth: ENC[AES256_GCM,data:5XTgV9PsM9S3LMT1SE8LfO9tvpL8IzirCeZYWtVMj2KT4mv6eK0edQ6EUhQGSTJsJWarkpnL7jSe0CwgaYMS34cZr0tmcIw1,iv:C2xaKN6+GDsZncP94atEPs7ElIEaYOtDKU5TVJpPVhw=,tag:rfr97Xc8V2H4jI0PIQTu4g==,type:str]
    type: Opaque
