apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: b44ed5542086cd85666b7faa4ba74554195dfb35e6cd32fed895ebfe3fd73fea
  name: cloudflare-api-token
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZVB2T2pwK2xNTHpqQ1lR

      dXhFalpzZUZrMWxvZXM4QU9Wd0pMTWF3RDM4CjMyckwyaExncjZhWUpDNTZWS2FK

      SzRpTndzNncxeHJ3akNLNXQ0SmtiNU0KLS0tIG9DNXhieUpGdkp3RnAvM2hOalJq

      VGo5K3licFQ1dEFoeDVjckU0b1RjcDQKCFKoFDeuDaJFKudiC2IFK3q32Zmui6j8

      CtZn2yVNydEm9wSilFUbqdbCc0aVAVajnV+yr8UbYfYE5g8B8tOJ0g==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T01:11:59Z'
  mac: ENC[AES256_GCM,data:DmRcSrbDfbfS0VqbjYhTtIb/jFzZ8JNFsu/NYXMRa3hnMH/ZnoABIoBAn5ZyqNRvrGlatTtf+FpEnKzhyVz4fmnyx8trhK6cbmCP237iyaXUwUd8i36+xf7MTr5Y9xjmNeNpY1H7tkRnjCzEDsKwfJ6RLkscx4phzxvU0qE3mbc=,iv:iKMNP+/Ugz0t7Y0eSAoEcM8F/B0rNVzVGVSUa3kAAUE=,tag:eb0HS4K3ERWOwDz1cCvbcQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: cloudflare-api-token
    stringData:
      auth: ENC[AES256_GCM,data:XxKBcgVv+3k6V4r+JcF5Tu/ochtuRDSqD5ImhRVtRMjrFf/LRaSyhw==,iv:PDs05BQov9A6Nho7jVMgaoxO0NVZUVx3vx7X29hOEIo=,tag:TIS66SioXbX8M7Jwn7CW+Q==,type:str]
    type: Opaque
