apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: f13b9aecc3fa23a29cb7165b3db0b03d42fe6cd58ff29d18440b466c59ebcda0
  name: cloudflare-api-token
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNXVDTzcwVW5ZRmgycDdQ

      RS9lcW0rUjllK0xWZ2QrUHZDUXBUNmx6Z0drCmJMMC8xWUNTY2JHZmxqOEY4YkQv

      QVJUVVhRckoyS0ZNK1pLRU9pZWMxOGcKLS0tIGwzQ0U3NXNQeWZYWmhDcWVWMjdN

      Y1FCV3FrSmIyUlAwdE5oczJEWUo1RFkKxlk3fwepV4WH8AVJRt+MKLJpjtJyEIMn

      SRkarvWEn8LZsvG11ROE4XvB1Wv4xx+Gn+9p2HgOjPne2J2Yqq3hvA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-20T01:33:29Z'
  mac: ENC[AES256_GCM,data:Tcas+MuWAVZLNaRCMS5ABwirpcYEXDwHX9HB8hjZBOR/tOSNuJWCPOy3hxi4yBATCpuhL7+TzhYH+wu4u92BtDMYj/aMDyNyY7SyTeiUzoNxn7vLj+FhOz1Z17BxEyq6F+O8CgCaEQfWxD5tDup7tQ5iDK7A5pBb3LjJ2KOB6r4=,iv:ws0DoFefRahEtlLxTMDZrcXXzr17Rfeb9KrW9FaVC54=,tag:MSKS8nI74mx8/2stl+DG0g==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
  - name: cloudflare-api-token
    stringData:
      cloudflare-api-token: ENC[AES256_GCM,data:gRvKDPrQxPRcaIjP6LUX25dbTQOylcvCdpescO3ceJY9Appq0fhRzA==,iv:x/9UGDplqvgHF/lJ302XLhIHfA7CX3p+iMtPmyiDEUw=,tag:kxHVxBrwtUHKr9DPhR0xcg==,type:str]
    type: Opaque
