apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    secrets.json64.dev/plaintext-sha256: b44ed5542086cd85666b7faa4ba74554195dfb35e6cd32fed895ebfe3fd73fea
  name: cloudflare-api-token
  namespace: cert-manager
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWNzci9mSFp5YytlUC9E

      bWdCVjNzd1N2ZGlkYVIyRnZ4b21hUHdyVDJBClRVb3NZTkVXalRQOTErazNIMEtx

      VGZPek90RzBiYzNCRm15WENxTzA3a2MKLS0tIFNJM2RsRGVCakZkL2QxU04yTUVQ

      WS9VUlpOb20wbkcyaW9oR1NmZGY0dmsKR3SNXKXKhGT2yFHlgem6mFdk2rPZU4tr

      SuwAG/7R0+A/moHX8cSWI8NePa6lVfvgYWa1Z6HViqlGeP7LXQg7+A==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1702hgudfz8y5ms3m4fukvvjhll7w9yeqk4tahewuv34t09rhd9sq756enl
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-02-19T00:57:33Z'
  mac: ENC[AES256_GCM,data:RSH9AKSdHO45Z+4nz+8A49z1b53i/HtvUBsdgD81K9xoB9NDDzETHyFTZ9mmxdET326lCpUud7LXzkQlU0T9HR2AkoH1dyoiyNvoiIytKetgsyM1V2NchacrqZ3BbU2BTSHYPhROvEB5bMupsTbKHwuigkbJExRIRSU3JaE55Ow=,iv:wO+yWYK3VJ7ZvFXfJGBXUHrdf+E9wOmbP1KLSRsrrxI=,tag:DEJbLosoJb1yBetPuR89VA==,type:str]
  pgp:
  - created_at: '2026-02-19T00:57:33Z'
    enc: '-----BEGIN PGP MESSAGE-----


      hQIMAwAAAAAAAAAAAQ/+NWgUULeBzJFByLlG04DviY+MJWuedwHAzu27Ly1CINEP

      1wPCMfw54yLNbeeD+ZROMHDc5JsKLRViZ3UAXklk91kzmO8ElkUhWq53fsgBxAH8

      pyKJCqaF22oQGo2bnjUtIcQGgELCgtdFFSgBqqfbUQLe8lmkXhuw3v6bOkU7CkrC

      pOP4no7K5Qfv4tzCUH8ez3VElOG5M3sXGOjMrJWImSBhXVXkCPQO2hZvGGEg/J3m

      wDl58DgzceFj7A6fchhWVnnPSxayzH4ABI225QG6z91lBiHvJTV9fWnyrvWp1/G5

      iazOqQsZXe17rcEcbJiU3zGnfsossflqOv2MktxRe5XqdyN03ty5xhnvlxNseXcL

      7vnB4wHNZUMN3XxOHiBhAxiijGoMoXqO7CmJC3Hs7IbaX+Ge55tEOUBwUzRERH2C

      RivYU2LkjcA/1xr3RQC7OpGBoKK648M01d+fZ+FHdWSTXFjeE5PwBKBNDDBwUNI5

      X1/fWMPCxT4CFs6H50oxRsOUa+njWEfLaWw7BdwvoSixv1M7R9hxAXRu7oCXATCQ

      ryO21anZ3+8H8ehDDO1dhCIxb9Rbpkwux2crWmBBxWwf+/7PYub4tm4GvyTq+Hir

      Apn/NT2R3e6LrgnDDD4LfyoO1JpjaPmHpGmwp2Qci8Ahxcyw2GEfUbyfNMl2P0nS

      XgHwMYmVSaKI6quUlYyrsYjz7xIdSgBEsRfWDm+TRhUWwWfwrcmLLub75RnUPXff

      gUvD0PkLBrVBmVlYRLg0ft/tVLL4HfGUiMqFPxKj6fe60TQbIigzExG7eRAfYTE=

      =X8PJ

      -----END PGP MESSAGE-----'
    fp: E822121B6A3D7FC6
  version: 3.11.0
spec:
  secretTemplates:
  - name: cloudflare-api-token
    stringData:
      auth: ENC[AES256_GCM,data:hvEIeLwz7lw0eiIyUOw/YRypHERXB3g/BjviLBaLuw3LLdqR7T/nkw==,iv:lUQQdTsq5cRgiTF2sd2jn5w24iRWhWbxVgKqNfp1grA=,tag:IqsMhaFiOhvqO+VXU8CgVQ==,type:str]
    type: Opaque
